Update text-fonts.md page to v3 methods
Intervention/docs pull request #35
Opened 2024-02-02 03:41 UTC by miguilimzero

This PR fixes the font methods in the documentation. It seems it's currently showing the v2 one.

- Updates methods to `set...`.
- Updates `align` and `valign` to `setAlignment` and `setValignment`.

2024-02-02 15:20 UTC, olivervogel requested changes

2024-02-02 15:20 UTC, olivervogel commented on image/v3/modifying/text-fonts.md
> +| font | callable|FontInterface | Callback function to configure the font appearance or `Typography\Font` instance. |
```suggestion
| font | callable or FontInterface | Callback function to configure the font appearance or `Typography\Font` instance. |
```
The pipe character interferes unfortunately with table generation.

2024-02-02 15:20 UTC, olivervogel commented on image/v3/modifying/text-fonts.md
> +    $font->setAngle(10);
Please revert. These were correct calls of class `Intervention\Image\Typography\FontFactory::class`.

2024-02-02 15:20 UTC, olivervogel commented on image/v3/modifying/text-fonts.md
> +FontInterface and listen to the following methods.
```suggestion
FontInterface and listens for following methods.
```
I think "listens" is correct. But "listens for" is better.

2024-02-02 15:20 UTC, olivervogel commented on image/v3/modifying/text-fonts.md
> +> public FontInterface::setSize(float $size): FontInterface
Please revert. This is correct call of class Intervention\Image\Typography\FontFactory::class.

2024-02-02 15:20 UTC, olivervogel commented on image/v3/modifying/text-fonts.md
> +> public FontInterface::setFilename(string $filename): FontInterface
Please revert. This is correct call of class Intervention\Image\Typography\FontFactory::class.

2024-02-02 15:20 UTC, olivervogel commented on image/v3/modifying/text-fonts.md
> +> public FontInterface::setColor(mixed $color): FontInterface
Please revert. This is correct call of class Intervention\Image\Typography\FontFactory::class.

2024-02-02 15:20 UTC, olivervogel commented on image/v3/modifying/text-fonts.md
> +> public FontInterface::setAlignment(string $align): FontInterface
Please revert. This is correct call of class Intervention\Image\Typography\FontFactory::class.

2024-02-02 15:20 UTC, olivervogel commented on image/v3/modifying/text-fonts.md
> +> public FontInterface::setValignment(string $valign): FontInterface
Please revert. This is correct call of class Intervention\Image\Typography\FontFactory::class.

2024-02-02 15:20 UTC, olivervogel commented on image/v3/modifying/text-fonts.md
> +> public FontInterface::setAngle(float $angle): FontInterface
Please revert. This is correct call of class Intervention\Image\Typography\FontFactory::class.

2024-02-02 15:20 UTC, olivervogel commented on image/v3/modifying/text-fonts.md
> +> public FontInterface::setLineHeight(float $height): FontInterface
Please revert. This is correct call of class Intervention\Image\Typography\FontFactory::class.

2024-02-02 15:24 UTC, olivervogel commented
Thank you. Some of the updates are not necessary, as they are calls from special helper classes.

2024-02-02 19:24 UTC, miguilimzero commented
Sorry @olivervogel. Totally my confusion. When I was upgrading my project to v3, I accidentally used `Font` to type the callable parameter, and the psalm accused the methods were wrong, making me investigate the classes and think that the documentation might be outdated. Sorry for you spending your time on this.

But another thing that made me think the documentation might be wrong is that the documentation says these methods are from the `FontInterfance` and not `FontFactory`. It's currently showing:

```md
### Font size

> public FontInterface::size(float $size): FontInterface
```

Shouldn't it be something like that:

```md
### Font size

> public FontFactory::size(float $size): FontFactory
```

2024-02-03 08:24 UTC, olivervogel commented
> But another thing that made me think the documentation might be wrong is that the documentation says these methods are from the `FontInterfance` and not `FontFactory`.

Yes, you are right.

2024-02-03 08:26 UTC, merged