Update drawing.md page to v3 methods
Intervention/docs pull request #36
Opened 2024-02-02 04:04 UTC by miguilimzero

Similar to #35

2024-02-02 15:24 UTC, olivervogel requested changes
Thank you. Some of the updates are not necessary, as they are calls from special helper classes.

2024-02-02 15:24 UTC, olivervogel commented on image/v3/modifying/drawing.md
> +    $rectangle->setBorder('white', 2); // border color & size of rectangle
Please revert. These were correct calls of class `Intervention\Image\Geometry\Factories\RectangleFactory::class`.

2024-02-02 15:24 UTC, olivervogel commented on image/v3/modifying/drawing.md
> +    $ellipse->setBorder('00f', 1); // border color & size
Please revert. These were correct calls of class `Intervention\Image\Geometry\Factories\EllipseFactory::class`.

2024-02-02 15:24 UTC, olivervogel commented on image/v3/modifying/drawing.md
> +    $circle->setBorder('b53717', 1); // border color & size
Please revert. These were correct calls of class `Intervention\Image\Geometry\Factories\CircleFactory::class`.

2024-02-02 15:24 UTC, olivervogel commented on image/v3/modifying/drawing.md
> +    $line->setWidth(5); // line width in pixels
Please revert. These were correct calls of class `Intervention\Image\Geometry\Factories\LineFactory::class`.

2024-02-02 15:24 UTC, olivervogel commented on image/v3/modifying/drawing.md
> +    $polygon->setBorder('#ff0', 6); // border color and border width
Please revert. These were correct calls of class `Intervention\Image\Geometry\Factories\PolygonFactory::class`.

2024-02-03 20:11 UTC, miguilimzero commented
@olivervogel Reverted the method changes and typed the callable parameters.

2024-02-04 08:40 UTC, olivervogel commented
> Reverted the method changes and typed the callable parameters.

Awesome! And thank you for your sponsorship! 💟

2024-02-04 08:40 UTC, merged